name: Tests workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip virtualenv
        virtualenv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install pylint
    - name: Analyse code with pylint - don't error out
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py') || true
    - name: Run tests with pytest
      run: |
        source .venv/bin/activate
        set -x

        : "Create dummy test config"
        cat <<EOF > epsmpcfg.yaml
        ssh:
          binary: ./tests/test_psmp.sh

        scp:
          binary: ./tests/test_psmp.sh
        EOF

        chmod +x ./tests/test_psmp.sh
        export EPSMP_PSW='vagrant'
        export EPSMP_TOTP_SECRET='BONOOW6FPJZAI6L7IZWW6B6445422VW5'

        pytest --verbose --capture=no

    # For debugging purposes only
    # - name: Archive debug log
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: epsmp-debug-log
    #     path: epsmp-dbglog.log
